
services:
  
  db: 
    image: postgres:latest
    container_name: postgresdb
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=springprojectdb'
      - 'POSTGRES_PASSWORD=posadmin'

  app:
    image: spring-project:latest
    container_name: spring-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    env_file: /src/main/resources/application.properties
    depends_on:
      - db
